### PR TITLE
Restructure to fix About page

### PR DESCRIPTION
**Pull request by MaxProfit**
Fixed the issue that I found with the about page not showing up by restructuring the exampleSite

### CODE REVIEW

**Comment by ashmitasusan** [comment]
Screenshot 2020-02-01 at 21 47 27

There's an issue when I try deploying the site! Can you please help?!

**Comment by MaxProfit** [comment]
@ashmitasusan I just ran it from a clean hugo install with no problems... Did you copy everything from exampleSite into the top directory of your project? It looks like the CSS and other static resources are not loading.

**Comment by ashmitasusan** [comment]
I am using R markdown to create this website. I have no problems previewing it from the R studio, but It doesn't work when I try deploying my website via Netlify.

**Comment by ashmitasusan** [comment]
Can you help me fix it?

**Comment by bjacquemet** [comment]
Hi @ashmitasusan,

Can you give us a bit more information? Some logs in the console? Is it your domain or the Netlify subdomain that doesn't show the CSS and static files?
Did you check if there was anything on Netlify's side? Is it an additional file to add (you can add `_headers` and `_redirects` files that might affect the deployment on Netlify)

**Pull request merged**
